name: cpplint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # prevent push event from triggering if it's part of a local PR, see
    # https://github.com/orgs/community/discussions/57827#discussioncomment-6579237
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint
      - name: Linting
        run: |
          cpplint --repository=. --recursive --filter=-build/c++11,-runtime/references,-readability/braces,-whitespace,-legal,-build/include ./src ./include ./lib/Hoymiles ./lib/MqttSubscribeParser ./lib/TimeoutHelper ./lib/ResetReason
